orbs:
  # https://github.com/react-native-community/react-native-circleci-orb
  rn: react-native-community/react-native@5.5.0
version: 2.1

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
  
workflows:
  build_android:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
      - rn/android_build:
          build_type: release
          requires:
            - analyse_js